"""Add community_role to communities_members

Revision ID: 075e6e4fab75
Revises: 4670c02fd96b
Create Date: 2025-09-25 13:18:11.714358

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '075e6e4fab75'
down_revision = '4670c02fd96b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('communities_members', schema=None) as batch_op:
        batch_op.add_column(sa.Column('community_role', sa.String(length=50), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('communities_members', schema=None) as batch_op:
        batch_op.drop_column('community_role')

    # ### end Alembic commands ###
