"""flare update new

Revision ID: 1f10db0b63b1
Revises: 55fd3426b9f8
Create Date: 2025-09-27 19:04:06.742671

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1f10db0b63b1'
down_revision = '55fd3426b9f8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Posts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('flair_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'community_flairs', ['flair_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Posts', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('flair_id')

    # ### end Alembic commands ###
