"""Fix CommunityMember relationships

Revision ID: 20ddb07c8ec5
Revises: ca69faf2566c
Create Date: 2025-10-07 13:30:31.489747

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '20ddb07c8ec5'
down_revision = 'ca69faf2566c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
