"""fix comment 

Revision ID: 7aba15026c12
Revises: 8dc9d2e881f7
Create Date: 2025-09-26 10:17:23.696915

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7aba15026c12'
down_revision = '8dc9d2e881f7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
