""" comment feedback link

Revision ID: 8dc9d2e881f7
Revises: 943fc7337413
Create Date: 2025-09-26 10:02:59.628839

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8dc9d2e881f7'
down_revision = '943fc7337413'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
