"""new

Revision ID: 943fc7337413
Revises: c19a62ab138f
Create Date: 2025-09-25 23:55:26.187355

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '943fc7337413'
down_revision = 'c19a62ab138f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Posts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('reasons', sa.String(length=10000), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Posts', schema=None) as batch_op:
        batch_op.drop_column('reasons')

    # ### end Alembic commands ###
