"""Add flair_id to Post

Revision ID: ca69faf2566c
Revises: 1f10db0b63b1
Create Date: 2025-09-27 19:36:47.827020

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ca69faf2566c'
down_revision = '1f10db0b63b1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
