"""Add community_role to communities_members

Revision ID: d27c94390995
Revises: 075e6e4fab75
Create Date: 2025-09-25 20:31:20.788279

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd27c94390995'
down_revision = '075e6e4fab75'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Posts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('status', sa.String(length=20), nullable=True))

    with op.batch_alter_table('communities_members', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('communities_members_community_id_fkey'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('communities_members_user_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'communities', ['community_id'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key(None, 'user', ['user_id'], ['id'], ondelete='CASCADE')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('communities_members', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('communities_members_user_id_fkey'), 'user', ['user_id'], ['id'])
        batch_op.create_foreign_key(batch_op.f('communities_members_community_id_fkey'), 'communities', ['community_id'], ['id'])

    with op.batch_alter_table('Posts', schema=None) as batch_op:
        batch_op.drop_column('status')

    # ### end Alembic commands ###
