"""TEST THE DB Migration

Revision ID: e02873f32243
Revises: 2da45162524d
Create Date: 2025-09-22 01:21:38.456712

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e02873f32243'
down_revision = '2da45162524d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('DB_CHECK_TEST',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('DB_CHECK_TEST')
    # ### end Alembic commands ###
