"""Add status column to Posts

Revision ID: e0d5bbb6f345
Revises: d27c94390995
Create Date: 2025-09-25 20:33:14.118821

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e0d5bbb6f345'
down_revision = 'd27c94390995'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
